let course,root=document.getElementById('root');
let state={screen:'today',mode:'learn',queue:[],i:0,chosen:null,ops:[]};
let progress=JSON.parse(localStorage.getItem('czechmn_v1')||'{}');
function save(){localStorage.setItem('czechmn_v1',JSON.stringify(progress))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function say(t){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='cs-CZ';u.rate=.78;speechSynthesis.speak(u)}
function all(){return course.lessons.flatMap((l,li)=>l[3].map((x,ci)=>({x,l,li,ci,id:li+'_'+ci})))}
function due(){let now=Date.now();return all().filter(v=>progress[v.id]?.due&&progress[v.id].due<=now)}
function fresh(){return all().filter(v=>!progress[v.id]).slice(0,10)}
function beginToday(){state={screen:'session',mode:'learn',queue:[...due(),...fresh()].slice(0,20),i:0,chosen:null,ops:[]};render()}
function rate(level){let v=state.queue[state.i];let mins={again:10,hard:60,good:1440,easy:4320}[level];progress[v.id]={level,due:Date.now()+mins*60000,seen:(progress[v.id]?.seen||0)+1};save();state.i++;state.chosen=null;state.ops=[];if(state.i>=state.queue.length)state.screen='done';render()}
function makeOptions(v){let wrong=all().filter(a=>a.id!==v.id).sort(()=>Math.random()-.5).slice(0,3).map(a=>a.x[1]);return [v.x[1],...wrong].sort(()=>Math.random()-.5)}
function chooseIndex(i){state.chosen=i;render()}
function home(){let d=due().length,n=fresh().length,m=Object.keys(progress).length;return `<section class="hero"><small>ӨНӨӨДӨР</small><h1>CzechMN</h1><p>Шинэ үг, давталт, сонсгол, тестийг нэг session-д хий.</p><b>Сурсан: ${m} · Давтах: ${d} · Шинэ: ${n}</b></section><section class="todayCard"><h2>Өнөөдрийн даалгавар</h2><p><b>${Math.min(10,n)}</b> шинэ үг + <b>${d}</b> давталт</p><p class="dim">Ойролцоогоор 10–15 минут</p><button class="start" onclick="beginToday()">Өнөөдрийн хичээл эхлэх</button></section><div class="tabs"><button class="active">Өнөөдөр</button><button onclick="state.screen='lessons';render()">Хичээлүүд</button><button onclick="state.screen='review';render()">Давтах (${d})</button><button onclick="state.screen='progress';render()">Ахиц</button></div>`}
function lessons(){return `<header class="lessonHead"><button onclick="state.screen='today';render()">←</button><div><b>Хичээлүүд</b></div></header><div class="lessons">${course.lessons.map((l,i)=>`<button class="lesson" onclick="startLesson(${i})"><span>${l[2]}</span><div><b>${esc(l[1])}</b><small>${l[3].length} карт</small></div><i>›</i></button>`).join('')}</div>`}
function startLesson(li){state={screen:'session',mode:'learn',queue:course.lessons[li][3].map((x,ci)=>({x,l:course.lessons[li],li,ci,id:li+'_'+ci})),i:0,chosen:null,ops:[]};render()}
function review(){let q=due();return `<header class="lessonHead"><button onclick="state.screen='today';render()">←</button><div><b>Давтах</b><small>${q.length} карт</small></div></header>${q.length?`<button class="start" onclick="state={screen:'session',mode:'learn',queue:due(),i:0,chosen:null,ops:[]};render()">Давталт эхлэх</button>`:'<p class="empty">Одоохондоо давтах карт алга.</p>'}`}
function progressView(){let p=Object.values(progress),good=p.filter(x=>x.level==='good'||x.level==='easy').length;return `<header class="lessonHead"><button onclick="state.screen='today';render()">←</button><div><b>Ахиц</b></div></header><section class="stats"><div><b>${p.length}</b><small>Сурсан карт</small></div><div><b>${good}</b><small>Тогтсон карт</small></div><div><b>${due().length}</b><small>Давтах карт</small></div></section><p class="dim">Ахиц энэ төхөөрөмж дээр хадгалагдана.</p>`}
function session(){let v=state.queue[state.i];if(!v)return '';let qmode=state.i%3===2;let pct=Math.round(state.i/state.queue.length*100);if(qmode){if(!state.ops.length)state.ops=makeOptions(v);let correct=v.x[1];return `<header class="lessonHead"><button onclick="state.screen='today';render()">×</button><div><b>${v.l[2]} ${esc(v.l[1])}</b><small>${state.i+1}/${state.queue.length}</small></div></header><div class="bar"><i style="width:${pct}%"></i></div><article class="quiz"><label>УТГЫГ СОНГО</label><h1>${esc(v.x[0])}</h1><button class="sound" onclick="say(${JSON.stringify(v.x[0])})">🔊 Сонсох</button><div class="opts">${state.ops.map((o,idx)=>`<button class="${state.chosen!==null?(o===correct?'ok':idx===state.chosen?'bad':''):''}" onclick="chooseIndex(${idx})">${esc(o)}</button>`).join('')}</div>${state.chosen!==null?`<button class="continue" onclick="rate(${state.ops[state.chosen]===correct?'good':'again'})">Үргэлжлүүлэх</button>`:''}</article>`}return `<header class="lessonHead"><button onclick="state.screen='today';render()">×</button><div><b>${v.l[2]} ${esc(v.l[1])}</b><small>${state.i+1}/${state.queue.length}</small></div></header><div class="bar"><i style="width:${pct}%"></i></div><article class="flash"><label>CZECH</label><div class="wordLine"><h1>${esc(v.x[0])}</h1><button onclick="say(${JSON.stringify(v.x[0])})">🔊</button></div><p class="pron">Дуудлага: ${esc(v.x[2])}</p><p class="meaning">${esc(v.x[1])}</p></article><div class="rates"><button onclick="rate('again')">Дахин<br><small>10 мин</small></button><button onclick="rate('hard')">Хэцүү<br><small>1 цаг</small></button><button onclick="rate('good')">Мэднэ<br><small>маргааш</small></button><button onclick="rate('easy')">Амархан<br><small>3 өдөр</small></button></div>`}
function done(){return `<section class="hero"><small>ДУУССАН</small><h1>Өнөөдрийн session дууслаа.</h1><p>${state.queue.length} карт боловсрууллаа.</p><button class="start" onclick="state.screen='today';render()">Нүүр рүү буцах</button></section>`}
function render(){let html=state.screen==='today'?home():state.screen==='lessons'?lessons():state.screen==='review'?review():state.screen==='progress'?progressView():state.screen==='session'?session():done();root.innerHTML=html}
fetch('./data/czech-course.json').then(r=>r.json()).then(d=>{course=d;render()}).catch(()=>root.innerHTML='<p class="error">Data ачаалж чадсангүй.</p>');