let course,state={screen:'home',lesson:0,card:0,flipped:false};const root=document.getElementById('root');
function say(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='cs-CZ';u.rate=.78;speechSynthesis.speak(u)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function home(){const total=course.lessons.reduce((n,l)=>n+l[3].length,0);return `<section class="hero"><small>МОНГОЛ → CZECH</small><h1>CzechMN</h1><p>Чех үг, утга, монгол дуудлагыг картаар сур.</p><b>${total} карт · ${course.lessons.length} бүлэг</b></section><h2>Хичээлүүд</h2><div class="lessons">${course.lessons.map((l,i)=>`<button class="lesson" onclick="openLesson(${i})"><span>${l[2]}</span><div><b>${esc(l[1])}</b><small>${l[3].length} карт</small></div><i>›</i></button>`).join('')}</div>`}
function openLesson(i){state={screen:'lesson',lesson:i,card:0,flipped:false};render()}
function move(n){let a=course.lessons[state.lesson][3];state.card=Math.max(0,Math.min(a.length-1,state.card+n));state.flipped=false;render()}
function flip(){state.flipped=!state.flipped;render()}
function lesson(){const l=course.lessons[state.lesson],a=l[3],x=a[state.card];let p=Math.round((state.card+1)/a.length*100);return `<header class="lessonHead"><button onclick="state.screen='home';render()">←</button><div><b>${l[2]} ${esc(l[1])}</b><small>${state.card+1} / ${a.length}</small></div></header><div class="bar"><i style="width:${p}%"></i></div><article class="flash ${state.flipped?'back':''}" onclick="flip()">${state.flipped?`<label>МОНГОЛ УТГА</label><h1>${esc(x[1])}</h1><p class="pron">Дуудлага: ${esc(x[2])}</p><small>Дахин дарж Czech үг рүү буцна</small>`:`<label>CZECH</label><div class="wordLine"><h1>${esc(x[0])}</h1><button onclick="event.stopPropagation();say(${JSON.stringify(x[0])})">🔊</button></div><small>Карт дээр дарж утгыг хар</small>`}</article><div class="nav"><button onclick="move(-1)" ${state.card===0?'disabled':''}>← Өмнөх</button><button onclick="move(1)" ${state.card===a.length-1?'disabled':''}>Дараах →</button></div>`}
function render(){root.innerHTML=state.screen==='home'?home():lesson()}
fetch('./data/czech-course.json').then(r=>r.json()).then(d=>{course=d;render()}).catch(()=>root.innerHTML='<p class="error">Data ачаалж чадсангүй.</p>');